INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('﻿Aarón Daniel', '﻿03/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Abigail Daniela', '04/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Abril Dante', '05/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Adrián David', '06/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Adriana Delfina', '07/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Agustín Diego', '08/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Agustina Diego Alejandro', '09/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Aitana Dylan', '10/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alan Eduardo', '11/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alejandra Elena', '12/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alejandro Elías', '13/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alessandra Elizabeth', '14/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alex Emilia', '15/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alexa Emiliano', '16/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alexander Emilio', '17/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Allison Emily', '18/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alma Emma', '19/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alonso Emmanuel', '20/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Álvaro Esteban', '21/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Amanda Fabiana', '22/08/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Amelia Facundo', '12/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ana Fátima', '13/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ana Paula Felipe', '14/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ana Sofia Fernando', '15/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Andrea Florencia', '16/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Andrés Francisco', '17/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ángel Franco', '18/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Anthony Gabriel', '19/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Antonella Gabriela', '20/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Antonia Gael', '21/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Antonio Guadalupe', '22/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ariadna Hugo', '23/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ariana Ian', '24/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ashley Ignacio', '25/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Axel Iker', '26/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Bautista Irene', '27/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Benjamín Isaac', '28/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Bianca Isabel', '29/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Bruno Isabella', '30/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Camila Isidora', '31/12/90');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Camilo Ivan', '01/01/91');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Carla Ivanna', '02/01/91');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Carlos Jacobo', '03/01/91');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Carolina Javier', '04/01/91');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Catalina Jazmín', '05/01/91');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Christian Jerónimo', '06/01/91');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Christopher Jesús', '07/01/91');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Clara Joaquín', '08/01/91');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Constanza Jorge', '20/09/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Cristóbal Josefa', '21/09/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Damián Josefina', '22/09/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Daniel Joshua', '23/09/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Daniela Josué', '24/09/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Dante Juan', '25/09/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('David Juan David', '26/09/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Delfina Juan Diego', '24/01/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Diego Juan Esteban', '25/01/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Diego Alejandro Juan José', '26/01/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Dylan Juan Manuel', '27/01/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Eduardo Juan Martín', '28/01/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Elena Juan Pablo', '29/01/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Elías Juan Sebastián', '30/01/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Elizabeth Juana', '31/01/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Emilia Julia', '01/02/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Emiliano Julián', '02/02/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Emilio Juliana', '03/02/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Emily Julieta', '04/02/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Emma Kevin', '05/02/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Emmanuel Laura', '06/02/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Esteban Lautaro', '07/02/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Fabiana Leonardo', '08/02/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Facundo Lola', '09/02/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Fátima Lorenzo', '10/02/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Felipe Luana', '11/02/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Fernando Lucas', '12/02/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Florencia Lucia', '13/02/02');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Francisco Luciana', '18/10/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Franco Luciano', '19/10/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Gabriel Luis', '20/10/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Gabriela Luna', '21/10/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Gael Magdalena', '22/10/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Guadalupe Maite', '23/10/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Hugo Malena', '24/10/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ian Manuel', '25/10/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ignacio Manuela', '26/10/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Iker María', '27/10/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Irene María Alejandra', '28/10/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Isaac María Camila', '29/10/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Isabel María Fernanda', '30/10/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Isabella Maria José', '31/10/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Isidora María Paula', '01/11/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ivan Mariana', '02/11/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ivanna Mariangel', '03/11/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Jacobo Mario', '04/11/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Javier Martín', '05/11/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Jazmín Martina', '06/11/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Jerónimo Mateo', '07/11/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Jesús Matías', '08/11/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Joaquín Matthew', '09/11/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Jorge Maximiliano', '10/11/85');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Josefa Máximo', '14/02/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Josefina Mía', '15/02/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Joshua Micaela', '16/02/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Josué Michelle', '17/02/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Juan Miguel', '18/02/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Juan David Miguel Ángel', '19/02/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Juan Diego Miranda', '20/02/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Juan Esteban Montserrat', '21/02/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Juan José Natalia', '22/02/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Juan Manuel Nicolás', '23/02/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Juan Martín Nicole', '24/02/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Juan Pablo Olivia', '25/02/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Juan Sebastián Pablo', '26/02/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Juana Paula', '27/02/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Julia Paulina', '28/02/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Julián Pedro', '01/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Juliana Rafael', '02/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Julieta Rafaela', '03/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Kevin Rebeca', '04/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Laura Regina', '05/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Lautaro Renata', '06/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Leonardo Ricardo', '07/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Lola Rodrigo', '08/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Lorenzo Romina', '09/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Luana Salomé', '10/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Lucas Samantha', '11/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Lucia Samuel', '12/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Luciana Santiago', '13/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Luciano Santino', '14/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Luis Sara', '15/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Luna Sara Sofía', '16/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Magdalena Sebastián', '17/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Maite Sergio', '18/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Malena Silvana', '19/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Manuel Simón', '20/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Manuela Sofia', '21/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('María Sophie', '22/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('María Alejandra Thiago', '23/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('María Camila Tomas', '24/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('María Fernanda Valentín', '25/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Maria José Valentina', '26/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('María Paula Valentino', '27/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Mariana Valeria', '28/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Mariangel Valery', '29/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Mario Vicente', '30/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Martín Aarón', '31/03/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Martina Abigail', '01/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Mateo Abril', '02/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Matías Adrián', '03/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Matthew Adriana', '04/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Maximiliano Agustín', '05/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Máximo Agustina', '06/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Mía Aitana', '07/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Micaela Alan', '08/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Michelle Alejandra', '09/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Miguel Alejandro', '10/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Miguel Ángel Alessandra', '11/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Miranda Alex', '12/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Montserrat Alexa', '13/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Natalia Alexander', '14/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Nicolás Allison', '15/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Nicole Alma', '16/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Olivia Alonso', '17/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Pablo Álvaro', '18/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Paula Amanda', '19/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Paulina Amelia', '20/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Pedro Ana', '21/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rafael Ana Paula', '22/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rafaela Ana Sofia', '23/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rebeca Andrea', '24/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Regina Andrés', '25/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Renata Ángel', '26/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ricardo Anthony', '27/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rodrigo Antonella', '28/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Romina Antonia', '29/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Salomé Antonio', '30/04/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Samantha Ariadna', '01/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Samuel Ariana', '02/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Santiago Ashley', '03/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Santino Axel', '04/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Sara Bautista', '05/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Sara Sofía Benjamín', '06/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Sebastián Bianca', '07/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Sergio Bruno', '08/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Silvana Camila', '09/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Simón Camilo', '10/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Sofia Carla', '11/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Sophie Carlos', '12/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Thiago Carolina', '13/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Tomas Catalina', '14/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Valentín Christian', '15/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Valentina Christopher', '16/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Valentino Clara', '17/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Valeria Constanza', '18/05/97');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Valery Cristóbal', '13/02/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Vicente Damián', '14/02/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Victoria Daniel', '15/02/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Violeta Daniela', '16/02/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ximena/Jimena Dante', '17/02/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Zoe David', '18/02/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Nicolás Delfina', '19/02/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Nicole Diego', '20/02/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Olivia Diego Alejandro', '21/02/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Pablo Dylan', '22/02/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Paula Eduardo', '23/02/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Paulina Elena', '24/02/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Pedro Elías', '25/02/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rafael Elizabeth', '26/02/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rafaela Emilia', '27/02/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rebeca Emiliano', '28/02/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Regina Emilio', '01/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Renata Emily', '02/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Nicolás Emma', '03/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Nicole Emmanuel', '04/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Olivia Esteban', '05/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Pablo Fabiana', '06/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Paula Facundo', '07/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Paulina Fátima', '08/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Pedro Felipe', '09/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rafael Fernando', '10/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rafaela Florencia', '11/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rebeca Francisco', '12/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Regina Franco', '13/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Renata Gabriel', '14/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Nicolás Gabriela', '15/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Nicole Gael', '16/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Olivia Guadalupe', '17/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Pablo Hugo', '18/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Paula Ian', '19/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Paulina Ignacio', '20/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Pedro Iker', '21/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rafael Irene', '22/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rafaela Isaac', '23/03/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rebeca Isabel', '31/01/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Regina Isabella', '01/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Renata Isidora', '02/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Nicolás Ivan', '03/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Nicole Ivanna', '04/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Olivia Jacobo', '05/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Pablo Javier', '06/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Paula Jazmín', '07/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Paulina Jerónimo', '08/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Pedro Jesús', '09/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rafael Joaquín', '10/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rafaela Jorge', '11/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rebeca Josefa', '12/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Regina Josefina', '13/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Renata Joshua', '14/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Aarón Josué', '15/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Abigail Juan', '16/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Abril Juan David', '17/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Adrián Juan Diego', '18/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Adriana Juan Esteban', '19/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Agustín Juan José', '20/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Agustina Juan Manuel', '21/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Aitana Juan Martín', '22/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alan Juan Pablo', '23/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alejandra Juan Sebastián', '24/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alejandro Juana', '25/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alessandra Julia', '26/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alex Julián', '27/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alexa Juliana', '28/02/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Aarón Julieta', '01/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Abigail Kevin', '02/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Abril Laura', '03/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Adrián Lautaro', '04/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Adriana Leonardo', '05/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Agustín Lola', '06/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Agustina Lorenzo', '07/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Aitana Luana', '08/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alan Lucas', '09/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alejandra Lucia', '10/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alejandro Luciana', '11/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alessandra Luciano', '12/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alex Luis', '13/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alexa Luna', '14/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Aarón Magdalena', '15/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Abigail Maite', '16/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Abril Malena', '17/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Adrián Manuel', '18/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Adriana Manuela', '19/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Agustín María', '20/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Agustina María Alejandra', '21/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Aitana María Camila', '22/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alan María Fernanda', '23/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alejandra Maria José', '24/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Sophia Wilian', '25/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Valentina Vitória', '26/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Maria Luiza Vinicios', '27/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Mariana Victor', '28/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Cecília Vicente', '29/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Emanuelly Valentina', '30/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Lavínia Tomás', '31/03/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Maria Tiago', '01/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ana Beatriz Sophia', '02/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Maria Fernanda Samuel', '03/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Catarina Sabrina', '04/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Beatriz Rodrigo', '05/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Helena Ricardo', '06/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Bianca Renato', '07/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Elisa Rafael', '08/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Giovana Pietro', '09/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Maitê Pedro', '10/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Laís Pedro', '11/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Larissa Paloma', '12/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Emanuelle Nicole', '13/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Maria Nicolas', '14/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Camila Nicolas', '15/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ester Muriel', '16/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Nicole Milene', '17/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Eduarda Matheus', '18/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Vitória Mateus', '19/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Amanda Marina', '20/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Laila Mariana', '21/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Aline Maria Luiza', '22/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Carolina Maria Fernanda', '23/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Anabela Maria', '24/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Marina Maria', '25/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Lia Maitê', '26/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ariana Lourenço', '27/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Débora Lorenzo', '28/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Anita Lia', '29/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Joana Leonardo', '30/04/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Daniela Lavínia', '01/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Paloma Larissa', '02/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Juliana Laís', '03/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Isa Laila', '04/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Sabrina Kelvin', '05/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Belinda Júlio', '06/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Milene Juliana', '07/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Flôr Jonas', '08/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Pedro João Pedro', '09/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Gabriel João Miguel', '10/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Matheus João Lucas', '11/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Heitor Joana', '12/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rafael Isaac', '13/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Nicolas Isa', '14/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Lorenzo Henrique', '15/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Felipe Helena', '16/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Henrique Heitor', '17/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('João Pedro Heitor', '18/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('João Lucas Gustavo', '19/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Eduardo Giovana', '20/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Leonardo Gabriel', '21/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Pietro Flôr', '22/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Benjamin Filipe', '23/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Isaac Fernando', '24/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Caio Felipe', '25/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('João Miguel Felipe', '26/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Vicente Fabrício', '27/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Antônio Ester', '28/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Enrico Enzo', '29/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Enzo Enrico', '30/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Heitor Emanuelly', '31/05/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Pedro Emanuelle', '01/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Gustavo Elisa', '02/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Nicolas Eduardo', '03/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Mateus Eduarda', '04/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Felipe Diogo', '05/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('David Débora', '06/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Daniel David', '07/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Samuel Danilo', '08/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Victor Daniela', '09/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Tomás Daniel', '10/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Tiago Cecília', '11/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Diogo Catarina', '12/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alexandre Carolina', '13/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Rodrigo Camila', '14/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Afonso Caio', '15/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Danilo Caetano', '16/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Vinicios Bianca', '17/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Filipe Benjamin', '18/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Lourenço Belinda', '19/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Fernando Beatriz', '20/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Kelvin Ariana', '21/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ângelo Antônio', '22/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ricardo Anita', '23/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Júlio Ângelo', '24/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Wilian Anabela', '25/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Fabrício Ana Beatriz', '26/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Muriel Amanda', '27/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alexander Aline', '28/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Jonas Alexandre', '29/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Renato Alexander', '30/06/98');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Adriano Afonso', '22/08/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Caetano Adriano', '23/08/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Sophia Isaac', '24/08/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Valentina Isa', '25/08/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Maria Luiza Henrique', '26/08/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Mariana Helena', '27/08/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Cecília Heitor', '28/08/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Emanuelly Heitor', '29/08/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Lavínia Gustavo', '30/08/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Maria Giovana', '31/08/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ana Beatriz Gabriel', '01/09/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Maria Fernanda Flôr', '02/09/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Catarina Filipe', '03/09/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Beatriz Fernando', '04/09/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Helena Felipe', '05/09/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Bianca Felipe', '06/09/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Elisa Fabrício', '07/09/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Giovana Ester', '08/09/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Maitê Enzo', '09/09/86');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Laís Enrico', '22/04/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Larissa Emanuelly', '23/04/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Emanuelle Emanuelle', '24/04/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Maria Elisa', '25/04/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Camila Eduardo', '26/04/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ester Eduarda', '27/04/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Nicole Diogo', '28/04/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Eduarda Débora', '29/04/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Vitória David', '30/04/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Amanda Danilo', '01/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Laila Daniela', '02/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Aline Daniel', '03/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Carolina Cecília', '04/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Anabela Catarina', '05/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Marina Carolina', '06/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Lia Camila', '07/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Ariana Caio', '08/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Débora Caetano', '09/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Anita Bianca', '10/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Joana Benjamin', '11/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Daniela Belinda', '12/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Paloma Beatriz', '13/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Juliana Ariana', '14/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Isa Antônio', '15/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Sabrina Anita', '16/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Belinda Ângelo', '17/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Milene Anabela', '18/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Flôr Ana Beatriz', '19/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Pedro Amanda', '20/05/01');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Gabriel Aline', '14/08/21');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Matheus Alexandre', '15/08/21');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Heitor Alexander', '16/08/21');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alexandre Afonso', '17/08/21');
INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO, DATA_ADMISSAO) VALUES ('Alexander Adriano', '18/08/21');
